project_name: erborist

release:
  prerelease: auto
  draft: false
  name_template: "erborist v{{.Version}}"

changelog:
  use: github-native
  sort: asc

before:
  hooks:
    - go mod tidy

builds:
  -
    main: ./internal
    binary: erborist
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    hooks:
      post:
        - npm run make:{{.Target}}

archives:
  - id: nix
    builds: [darwin, linux]
    <<: &archive_defaults
      rlcp: true
      name_template: >-
        {{ .ProjectName }}_
        {{- .Version }}_
        {{- if eq .Os "darwin" }}macos{{ else }}{{ .Os }}{{ end }}_
        {{- .Arch }}
        {{- with .Arm }}v{{ . }}{{ end }}
        {{- with .Mips }}_{{ . }}{{ end }}
        {{- if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}
    wrap_in_directory: true
    format: tar.gz
    files:
      - LICENSE
  - id: win
    builds: [windows]
    <<: *archive_defaults
    wrap_in_directory: false
    format: zip
    files:
      - LICENSE
