project_name: erborist

release:
  prerelease: auto
  draft: false
  name_template: "erborist v{{.Version}}"

changelog:
  use: github-native
  sort: asc

before:
  hooks:
    - go mod tidy

builds:
  - id: windows
    main: ./internal
    binary: erborist
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    hooks:
      post:
        - npm run make:{{.Target}}

  - id: linux
    main: ./internal
    binary: erborist
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    hooks:
      post:
        - npm run make:{{.Target}}

  - id: macos
    main: ./internal
    binary: erborist
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    hooks:
      post:
        - npm run make:{{.Target}}
        - cmd: |
            quill
              sign "{{.Path}}"
              --dry-run={{.IsSnapshot}}
              --ad-hoc=true
              -vv

# Docs at https://goreleaser.com/customization/sign
signs:
  - signature: "${artifact}.sig"
    cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    certificate: '{{ trimsuffix (trimsuffix .Env.artifact ".zip") ".tar.gz" }}.pem'
    args:
      - sign-blob
      - "--yes"
      - '--oidc-issuer={{if index .Env "CI"}}https://token.actions.githubusercontent.com{{else}}https://oauth2.sigstore.dev/auth{{end}}'
      - "--output-signature=${signature}"
      - "--output-certificate=${certificate}"
      - "${artifact}"
    artifacts: all
    output: true

archives:
  -
    <<: &archive_defaults
      rlcp: true
      name_template: >-
        {{ .ProjectName }}_
        {{- .Version }}_
        {{- if eq .Os "darwin" }}macos{{ else }}{{ .Os }}{{ end }}_
        {{- .Arch }}
        {{- with .Arm }}v{{ . }}{{ end }}
        {{- with .Mips }}_{{ . }}{{ end }}
        {{- if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}
    wrap_in_directory: true
    format: tar.gz
    files:
      - LICENSE
    format_overrides:
      - goos: windows
        format: zip
