name: building

on:
  push:
    paths:
      - "**.js"
      - package.json
      - package-lock.json
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  contents: read

jobs:
  make:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - uses: actions/cache@v3
        with:
          path: ~/.pkg-cache/
          key: ubuntu-latest-18.x

      - run: npm install

      - run: npm run make

      - name: Archive binaries
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: dist/
          retention-days: 1

  test-linux:
    name: 'test binary (linux, x64)'
    if: github.event.pull_request.draft == false
    needs: make
    runs-on: ubuntu-latest
    steps:

      - name: Get binaries
        uses: actions/download-artifact@v3
        with:
          name: binaries
          path: dist/

      - name: Check file
        run: |
          ls -l dist/erborist_linux_amd64_v1/erborist
          file dist/erborist_linux_amd64_v1/erborist

      - name: Execute binary
        run: |
          chmod +x ./dist/erborist_linux_amd64_v1/erborist
          ./dist/erborist_linux_amd64_v1/erborist --help

  test-darwin:
    name: 'test binary (macos, x64)'
    if: github.event.pull_request.draft == false
    needs: make
    runs-on: macos-latest
    steps:

      - name: Get binaries
        uses: actions/download-artifact@v3
        with:
          name: binaries
          path: dist/

      - name: Check file
        run: |
          ls -l dist/erborist_darwin_amd64_v1/erborist
          file dist/erborist_darwin_amd64_v1/erborist

      - name: Execute binary
        run: |
          chmod +x ./dist/erborist_darwin_amd64_v1/erborist
          ./dist/erborist_darwin_amd64_v1/erborist --help

  test-win:
    name: 'test binary (windows, x64)'
    if: github.event.pull_request.draft == false
    needs: make
    runs-on: windows-latest
    steps:

      - name: Get binaries
        uses: actions/download-artifact@v3
        with:
          name: binaries
          path: dist/

      - name: Execute binary
        run: ./dist/erborist_windows_amd64_v1/erborist.exe --help

