name: releasing

on:
  pull_request:
    tags:
     - "v*"
  push:
    tags:
      - "v*"

permissions:
  id-token: write
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:

      - name: Check out the source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Avoid running against a shallow clone

      - name: Force fetch upstream tags
        run: git fetch --force --tags

      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Restore the Go modules cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: go-${{ runner.os }}-${{ hashFiles('go.mod') }}
          restore-keys: |
            go-${{ runner.os }}-

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - uses: actions/cache@v3
        with:
          path: ~/.pkg-cache/
          key: ubuntu-latest-18.x

      - run: npm install

      - name: Check git status
        run: git diff --exit-code

      - name: Install quill
        run: curl -sSfL https://raw.githubusercontent.com/anchore/quill/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Install cosign
        uses: sigstore/cosign-installer@v3.0.1

      - name: Release
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COSIGN_EXPERIMENTAL: 1