name: testing

on:
  push:
    paths:
      - "**.js"
      - package.json
      - package-lock.json
    branches: ['main']
  pull_request:
    paths:
      - "**.go"
      - package.json
      - package-lock.json
    branches: ['main']

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - uses: actions/cache@v3
        with:
          path: ~/.pkg-cache/
          key: ubuntu-latest-18.x

      - run: npm install

      - run: npm run coverage

      - name: Create coverage report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/cobertura-coverage.xml
          format: markdown
          output: both

      - name: Comment PR with coverage report
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
